=== atricore/atricore-idbus/console-liveservices/liveupdate/support/atricore-liveupdate-v1.0/src/main/resources/atricore-liveupdate-md-1.0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
  ~ Atricore IDBus
  ~
  ~ Copyright 2009, Atricore Inc.
  ~
  ~ This is free software; you can redistribute it and/or modify it
  ~ under the terms of the GNU Lesser General Public License as
  ~ published by the Free Software Foundation; either version 2.1 of
  ~ the License, or (at your option) any later version.
  ~
  ~ This software is distributed in the hope that it will be useful,
  ~ but WITHOUT ANY WARRANTY; without even the implied warranty of
  ~ MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
  ~ Lesser General Public License for more details.
  ~
  ~ You should have received a copy of the GNU Lesser General Public
  ~ License along with this software; if not, write to the Free
  ~ Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
  ~ 02110-1301 USA, or see the FSF site: http://www.fsf.org.
  -->

<schema
        targetNamespace="urn:com:atricore:liveservices:liveupdate:1.0:md"
        xmlns="http://www.w3.org/2001/XMLSchema"
        xmlns:ds="http://www.w3.org/2000/09/xmldsig#"
        xmlns:xenc="http://www.w3.org/2001/04/xmlenc#"
        xmlns:lu="urn:com:atricore:liveservices:liveupdate:1.0:md"
        elementFormDefault="unqualified"
        attributeFormDefault="unqualified"
        blockDefault="substitution"
        version="2.0">

    <import namespace="http://www.w3.org/2000/09/xmldsig#"
            schemaLocation="http://www.josso.org/schema/www.w3.org/TR/2002/REC-xmldsig-core-20020212/xmldsig-core-schema.xsd"/>
    <import namespace="http://www.w3.org/2001/04/xmlenc#"
            schemaLocation="http://www.josso.org/schema/www.w3.org/TR/2002/REC-xmlenc-core-20021210/xenc-schema.xsd"/>

    <annotation>
        <documentation>
            Document identifier: atricore-liveupdate-md-1.0
            Revision history:
            V1.0 (October, 2010):
            Initial Standard Schema.
        </documentation>
    </annotation>

    <element name="artifactDescriptor" type="lu:ArtifactDescriptorType"/>
    <complexType name="ArtifactDescriptorType">
        <sequence>
            <element ref="ds:Signature" minOccurs="0"/>
            <element ref="lu:artifact"/>
        </sequence>
        <attribute name="checksum" type="string" use="optional"/>
        <attribute name="lastUpdate" type="dateTime" use="optional"/>
    </complexType>

    <element name="updatesIndex" type="lu:UpdatesIndexType"/>
    <complexType name="UpdatesIndexType">
        <sequence>
            <element ref="ds:Signature" minOccurs="0"/>
            <element ref="lu:updateDescriptor" minOccurs="0" maxOccurs="unbounded"/>
        </sequence>
        <attribute name="ID" type="ID" use="required"/>
    </complexType>

    <element name="updateDescriptor" type="lu:UpdateDescriptorType"/>
    <complexType name="UpdateDescriptorType">
        <sequence>
            <element ref="lu:installableUnit" minOccurs="0" />
        </sequence>
        <attribute name="ID" type="ID" use="required"/>
        <attribute name="description" type="string" use="required"/>
        <attribute name="IssueInstant" type="dateTime" use="required"/>
    </complexType>

    <element name="installableUnit" type="lu:InstallableUnitType"/>
    <complexType name="InstallableUnitType">
        <sequence>
            <element ref="lu:artifact" minOccurs="0" maxOccurs="unbounded"/>
            <element ref="lu:requirement" minOccurs="0" maxOccurs="unbounded"/>
            <element ref="lu:updateDescriptor" minOccurs="0"/>
        </sequence>
        <attribute name="ID" type="ID" use="required"/>
        <attribute name="group" type="string" use="required" />
        <attribute name="name" type="string" use="required" />
        <attribute name="version" type="string" use="required" />
        <attribute name="updateNature" type="lu:UpdateNatureType" />
        <attribute name="description" type="string"/>

    </complexType>

    <element name="versionRange" type="lu:VersionRangeType"/>
    <complexType name="VersionRangeType">
        <attribute name="Expression" type="string" use="required"/>
    </complexType>

    <complexType name="RequirementType">
        <attribute name="description" type="string"/>
    </complexType>

    <element name="requirement" type="lu:RequiredFeatureType"/>
    <complexType name="RequiredFeatureType">
        <complexContent>
            <extension base="lu:RequirementType">
                <sequence>
                    <element ref="lu:versionRange" />
                </sequence>
                <attribute name="group" type="string" use="required"/>
                <attribute name="name" type="string" use="required"/>
            </extension>
        </complexContent>
    </complexType>

    <element name="artifact" type="lu:ArtifactKeyType"/>
    <complexType name="ArtifactKeyType">
        <attribute name="ID" type="ID" use="required"/>
        <attribute name="group" type="string" use="required"/>
        <attribute name="name" type="string" use="required"/>
        <attribute name="version" type="string" use="required"/>
        <attribute name="classifier" type="string" use="optional"/>
        <attribute name="type" type="string" use="optional"/>
    </complexType>

    <simpleType name="UpdateNatureType">
        <restriction base="string">
            <enumeration value="SECURITY"/>
            <enumeration value="BUGFIX"/>
            <enumeration value="EMERGENCY_BUGFIX"/>
            <enumeration value="IMPROVEMENT"/>
            <enumeration value="NEW_FEATURE"/>
            <enumeration value="UPGRADE"/>
            <enumeration value="SERVICE_PACK"/>
            <enumeration value="DISTRO"/>
        </restriction>
    </simpleType>

    <!-- RFU -->
    <element name="Request" type="lu:RequestType"/>
    <complexType name="RequestType">
        <attribute name="ID" type="ID" use="required"/>
        <attribute name="IssueInstant" type="dateTime" use="required"/>
    </complexType>

    <element name="Response" type="lu:ResponseType"/>
    <complexType name="ResponseType">
        <attribute name="ID" type="ID" use="required"/>
        <attribute name="IssueInstant" type="dateTime" use="required"/>
    </complexType>

</schema>

=== atricore/atricore-idbus/console-liveservices/liveupdate/main/src/test/resources/com/atricore/idbus/console/liveservices/liveupdate/main/test/dependency-tree-test-update-02.xml
<?xml version="1.0" encoding="UTF-8"?>

<updatesIndex xmlns="urn:com:atricore:liveservices:liveupdate:1.0:md"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="urn:com:atricore:liveservices:liveupdate:1.0:md
                    http://www.atricore.com/liveservices/liveupdate/atricore-liveupdate-md-1.0.xsd"
        ID="id0000001100">

    <updateDescriptor ID="id0000000100" description="JOSSO 2 EE ${pom.version}" IssueInstant="2010-12-25T19:32:52Z">

        <installableUnit ID="id0000000110"
                         group="${pom.groupId}"
                         name="${pom.artifactId}"
                         version="${pom.version}"
                         description="JOSSO 2 EE"
                         updateNature="UPGRADE">



            <!-- Set of artifacts required for this install -->

            <!-- JOSSO 2 EE Update (distribution) -->
            <artifact ID="id0000000111"
                      group="${pom.groupId}"
                      name="josso-ee"
                      version="${pom.version}"
                      type="tar.gz"
                      classifier="liveupdate"/>

            <!-- JOSSO 2 EE Update (distribution) -->
            <artifact ID="id0000000112"
                      group="${pom.groupId}"
                      name="josso-ee"
                      version="${pom.version}"
                      type="zip"
                      classifier="liveupdate"/>


            <!-- JOSSO 2 EE Update (liveupdate installer) -->
            <artifact ID="id0000000113"
                      group="${pom.groupId}"
                      name="${pom.artifactId}"
                      version="${pom.version}"
                      type="bundle"
                      classifier="liveupdate"/>


            <!-- Required features -->
            <requirement group="${pom.groupId}" name="josso-ee" description="JOSSO 2 EE 2.0.0" >
                <versionRange Expression="[1.9,2.0)"/>
            </requirement>

        </installableUnit>

    </updateDescriptor>

</updatesIndex>

=== atricore/atricore-idbus/console-liveservices/liveupdate/main/src/test/resources/com/atricore/idbus/console/liveservices/liveupdate/main/test/test-updates.xml
<?xml version="1.0" encoding="UTF-8"?>

<updatesIndex xmlns="urn:com:atricore:liveservices:liveupdate:1.0:md"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="urn:com:atricore:liveservices:liveupdate:1.0:md
                    http://www.atricore.com/liveservices/liveupdate/atricore-liveupdate-md-1.0.xsd"
        ID="id0000001200">

    <updateDescriptor ID="id0000000200" description="JOSSO 2 EE ${pom.version}" IssueInstant="2010-12-25T19:32:52Z">

        <installableUnit ID="id0000000120" group="${pom.groupId}" name="${pom.artifactId}" updateNature="UPGRADE">

            <version Version="${pom.version}"/>

            <!-- Provided Features -->
            <feature ID="id000000232" group="${pom.groupId}" name="josso-ee" description="JOSSO 2 EE ${pom.version}">
                <version Version="${pom.version}"/>
            </feature>

            <!-- Set of artifacts required for this install -->

            <!-- JOSSO 2 EE Update (distribution) -->
            <artifact ID="id0000000121" group="${pom.groupId}" name="josso-ee" version="${pom.version}" classifier="liveupdate"/>

            <!-- JOSSO 2 EE Update (liveupdate installer) -->
            <artifact ID="id0000000122" group="${pom.groupId}" name="josso-ee" version="${pom.version}" classifier="install"/>


            <!-- Required features -->
            <requirement group="${pom.groupId}" name="josso-ee" description="JOSSO 2 EE 2.0.0" >
                <versionRange Expression="[1.9,2.0)"/>
            </requirement>

        </installableUnit>

    </updateDescriptor>

</updatesIndex>

=== atricore/atricore-idbus/console-liveservices/liveupdate/support/atricore-liveupdate-v1.0/src/test/resources/com/atricore/liveservices/liveupdate/_1_0/util/test/test-updates.xml
<?xml version="1.0" encoding="UTF-8"?>

<updatesIndex xmlns="urn:com:atricore:liveservices:liveupdate:1.0:md"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="urn:com:atricore:liveservices:liveupdate:1.0:md
                    http://www.atricore.com/liveservices/liveupdate/atricore-liveupdate-md-1.0.xsd"
        ID="id0000001100">

<<<<<<< HEAD
    <updateDescriptor ID="id0000000200" description="JOSSO 2 EE 1.3.0-SNAPSHOT" IssueInstant="2010-12-25T19:32:52Z">
=======
    <updateDescriptor ID="id0000000200" description="JOSSO 2 EE 1.2.1-SNAPSHOT" IssueInstant="2010-12-25T19:32:52Z">
>>>>>>> 1.2.1

        <installableUnit ID="id0000000110"
                         group="com.atricore.josso"
                         name="com.atricore.josso.ee.install"
<<<<<<< HEAD
                         version="1.3.0-SNAPSHOT"
=======
                         version="1.2.1-SNAPSHOT"
>>>>>>> 1.2.1
                         description="JOSSO 2 EE"
                         updateNature="UPGRADE">



            <!-- Set of artifacts required for this install -->

            <!-- JOSSO 2 EE Update (distribution) -->
            <artifact ID="id0000000111"
                      group="com.atricore.josso"
                      name="josso-ee"
<<<<<<< HEAD
                      version="1.3.0-SNAPSHOT"
=======
                      version="1.2.1-SNAPSHOT"
>>>>>>> 1.2.1
                      type="tar.gz"
                      classifier="liveupdate"/>

            <!-- JOSSO 2 EE Update (distribution) -->
            <artifact ID="id0000000112"
                      group="com.atricore.josso"
                      name="josso-ee"
<<<<<<< HEAD
                      version="1.3.0-SNAPSHOT"
=======
                      version="1.2.1-SNAPSHOT"
>>>>>>> 1.2.1
                      type="zip"
                      classifier="liveupdate"/>


            <!-- JOSSO 2 EE Update (liveupdate installer) -->
            <artifact ID="id0000000113"
                      group="com.atricore.josso"
                      name="com.atricore.josso.ee.install"
<<<<<<< HEAD
                      version="1.3.0-SNAPSHOT"
=======
                      version="1.2.1-SNAPSHOT"
>>>>>>> 1.2.1
                      type="bundle"
                      classifier="liveupdate"/>


            <!-- Required features -->
            <requirement group="com.atricore.josso" name="josso-ee" description="JOSSO 2 EE 2.0.0" >
                <versionRange Expression="[1.9,2.0)"/>
            </requirement>

        </installableUnit>

    </updateDescriptor>

</updatesIndex>
